<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="AnalogOut" Id="{53b4ccd0-b970-46d7-b218-47ae86916403}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK AnalogOut EXTENDS FB_AnalogOutput
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>