<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="PWM_Output" Id="{563ecf95-0183-4061-b981-aa77c1abbdf1}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PWM_Output
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>